spring.application.name=notification-service
server.port=8080

# ==================================
# Kafka
# ==================================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

# TEMPORARY - Don't start Kafka listener yet
spring.kafka.listener.auto-startup=true

spring.kafka.consumer.group-id=notificationService
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.type.mapping=event:com.techie.microservices.notification.order.event.OrderPlacedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.techie.microservices.notification.order.event

# ==================================
# Spring Boot SSL Bundle (PEM)
# ==================================
spring.ssl.bundle.pem.kafka.keystore.certificate=file:/etc/secrets/service.cert
spring.ssl.bundle.pem.kafka.keystore.private-key=file:/etc/secrets/service-key-pkcs8.pem
spring.ssl.bundle.pem.kafka.truststore.certificate=file:/etc/secrets/ca.pem

spring.kafka.ssl.bundle=kafka
spring.kafka.properties.security.protocol=SSL

# ==================================
# Mailtrap
# ==================================
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ==================================
# Actuator
# ==================================
management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=always

# ==================================
# Debug
# ==================================
logging.level.org.springframework.boot.ssl=DEBUG
logging.level.org.apache.kafka=INFO