spring.application.name=notification-service
server.port=8080

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.consumer.group-id=notificationService
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# IMPORTANT: use the package where OrderPlacedEvent actually exists
spring.kafka.consumer.properties.spring.json.type.mapping=event:com.techie.microservices.notification.order.event.OrderPlacedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.techie.microservices.notification.order.event

# Aiven SSL (PEM)
spring.kafka.properties.security.protocol=SSL
spring.kafka.properties.ssl.truststore.type=PEM
spring.kafka.properties.ssl.truststore.location=/etc/secrets/ca.pem

# Present client certificate to Aiven
spring.kafka.properties.ssl.keystore.type=PEM
spring.kafka.properties.ssl.keystore.certificate.chain=/etc/secrets/service.cert
spring.kafka.properties.ssl.keystore.key=/etc/secrets/service-key-pkcs8.pem

logging.level.org.apache.kafka.common.security.ssl=DEBUG
# Mail
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
