spring.application.name=product-service
server.port=8080

# ===============================
# MongoDB
# ===============================
spring.data.mongodb.uri=${MONGODB_URI}

# ===============================
# Inventory Service URL
# ===============================
inventory.service.url=${INVENTORY_SERVICE_URL}

# ===============================
# Swagger
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always